### ISSUE TITLE
Error when using Api-admin

### ISSUE THREAD

**Issue by Dannebicque** [api-platform/admin#26]
I have install ApiPlatform (with composer), and then install Api-Admin.

When I run the front (yarn start), I have several errors 

```
Warning: Unknown prop `onTouchTap` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in button
    in EnhancedButton
    in IconButton
    in div
    in Paper
    in AppBar
    in AppBar
    in Connect(AppBar)
    in MuiComponent
    in div
    in div
    in MuiThemeProvider
    in Layout
    in EventListener
    in WithWidth
    in Connect(WithWidth)
    in Route
    in Switch
    in div
    in Router
    in ConnectedRouter
    in TranslationProvider
    in withContext(TranslationProvider)
    in Connect(withContext(TranslationProvider))
    in Provider
    in Admin
    in _class
    in _class (at App.js:6)
    in App (at index.js:7)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:36
warning @ warning.js:60
warnUnknownProperties @ ReactDOMUnknownPropertyHook.js:86
handleElement @ ReactDOMUnknownPropertyHook.js:99
onBeforeMountComponent @ ReactDOMUnknownPropertyHook.js:104
callHook @ ReactDebugTool.js:27
emitEvent @ ReactDebugTool.js:39
onBeforeMountComponent @ ReactDebugTool.js:316
mountComponent @ ReactReconciler.js:42
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
_updateRenderedComponent @ ReactCompositeComponent.js:764
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
../node_modules/react/lib/ReactComponent.js.ReactComponent.setState @ ReactComponent.js:63
(anonymous) @ HydraAdmin.js:30
invariant.js:44 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (invariant.js:44)
    at Object.addComponentAsRefTo (ReactOwner.js:68)
    at attachRef (ReactRef.js:23)
    at Object../node_modules/react-dom/lib/ReactRef.js.ReactRef.attachRefs (ReactRef.js:42)
    at ReactCompositeComponentWrapper.attachRefs (ReactReconciler.js:23)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:209)
    at ReactReconcileTransaction.perform (Transaction.js:156)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:143)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at flushBatchedUpdates (ReactUpdates.js:172)
    at ReactUpdatesFlushTransaction.close (ReactUpdates.js:47)
    at ReactUpdatesFlushTransaction.closeAll (Transaction.js:209)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:156)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at flushBatchedUpdates (ReactUpdates.js:172)
    at ReactUpdatesFlushTransaction.close (ReactUpdates.js:47)
    at ReactUpdatesFlushTransaction.closeAll (Transaction.js:209)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:156)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at Object.flushBatchedUpdates (ReactUpdates.js:172)
    at ReactDefaultBatchingStrategyTransaction.closeAll (Transaction.js:209)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:156)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.enqueueUpdate (ReactUpdates.js:200)
    at enqueueUpdate (ReactUpdateQueue.js:24)
    at Object.enqueueSetState (ReactUpdateQueue.js:218)
    at _class.../node_modules/react/lib/ReactComponent.js.ReactComponent.setState (ReactComponent.js:63)
    at HydraAdmin.js:30
    at <anonymous>
invariant @ invariant.js:44
addComponentAsRefTo @ ReactOwner.js:68
attachRef @ ReactRef.js:23
./node_modules/react-dom/lib/ReactRef.js.ReactRef.attachRefs @ ReactRef.js:42
attachRefs @ ReactReconciler.js:23
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
../node_modules/react/lib/ReactComponent.js.ReactComponent.setState @ ReactComponent.js:63
(anonymous) @ HydraAdmin.js:30
proxyConsole.js:56 uncaught at handleFetch Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (http://localhost:3000/static/js/bundle.js:120583:15)
    at Object.removeComponentAsRefFrom (http://localhost:3000/static/js/bundle.js:142112:36)
    at detachRef (http://localhost:3000/static/js/bundle.js:142596:16)
    at Object../node_modules/react-dom/lib/ReactRef.js.ReactRef.detachRefs (http://localhost:3000/static/js/bundle.js:142648:5)
    at Object.unmountComponent (http://localhost:3000/static/js/bundle.js:142464:14)
    at Object.unmountChildren (http://localhost:3000/static/js/bundle.js:135292:25)
    at ReactDOMComponent.unmountChildren (http://localhost:3000/static/js/bundle.js:141893:28)
    at ReactDOMComponent.unmountComponent (http://localhost:3000/static/js/bundle.js:137428:10)
    at Object.unmountComponent (http://localhost:3000/static/js/bundle.js:142465:22)
    at ReactCompositeComponentWrapper.unmountComponent (http://localhost:3000/static/js/bundle.js:135822:23)
    at Object.unmountComponent (http://localhost:3000/static/js/bundle.js:142465:22)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:135276:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:141728:32)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:141832:31)
    at ReactDOMComponent.updateChildren (http://localhost:3000/static/js/bundle.js:141819:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/static/js/bundle.js:137380:12)
    at ReactDOMComponent.updateComponent (http://localhost:3000/static/js/bundle.js:137198:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/static/js/bundle.js:137160:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:135255:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:141728:32)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:141832:31)
    at ReactDOMComponent.updateChildren (http://localhost:3000/static/js/bundle.js:141819:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/static/js/bundle.js:137380:12)
    at ReactDOMComponent.updateComponent (http://localhost:3000/static/js/bundle.js:137198:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/static/js/bundle.js:137160:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:136158:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:136128:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:136049:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:135951:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:136158:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:136128:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:136049:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:135951:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:136158:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:136128:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:136049:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:135951:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:136158:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:136128:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:136049:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:135951:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:142511:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:136158:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:136128:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:136049:12)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
log @ utils.js:216
(anonymous) @ proc.js:473
exec @ scheduler.js:20
flush @ scheduler.js:61
asap @ scheduler.js:34
runPutEffect @ proc.js:466
runEffect @ proc.js:421
next @ proc.js:302
currCb @ proc.js:375
```
If I click, nothing append. But If I load the direct URL, It's OK.
Communication with API is also OK (data are saved in the database).

**Comment by dunglas** [comment]
The error is this one `invariant.js:44 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`.

Can you paste your `packages.json` file and the output of `yarn list react` please?

**Comment by Dannebicque** [comment]
yarn list v0.24.5
└─ react@15.6.1
✨  Done in 1.39s.

and package.json

```
{
  "name": "my-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts": "1.0.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by dunglas** [comment]
Ok, you need to downgrade to React 15.5 until Admin On Rest add support for it.

**Comment by Dannebicque** [comment]
I Try with this package.json

```
{
  "name": "my-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "15.5.0",
    "react-dom": "15.5.0",
    "react-scripts": "1.0.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Same errors. I wait for an update of Admin-On-rest.

Thanks

**Comment by dunglas** [comment]
Try with this:

```
    "react": "~15.5.4",
    "react-dom": "~15.5.4"
```

And don't forget to run `yarn upgrade` then to restart the dev server.

**Comment by davidpodhola** [comment]
Sorry, still did not helped. I even tried

    "react": "15.5.4",
    "react-dom": "15.5.4",
    "react-scripts": "1.0.0"

, but still no luck.

**Comment by dunglas** [comment]
Can you try to just remove those lines:

```
"react": "15.5.4",
"react-dom": "15.5.4",
```

**Comment by davidpodhola** [comment]
Yes! This removed the issue with `Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)`.

Now there is this strange issue with the first letter being omitted from the entity name see the screenshot (the entity is `Foo`).
![screenshot from 2017-09-27 11-02-41](https://user-images.githubusercontent.com/436605/30904871-807cefea-a373-11e7-97a9-5c9fd1189de6.png)
What did I wrong here?

**Comment by dunglas** [comment]
Wow this one is really weird. Can you try to add another entity just to see if the problem still occurs?

**Comment by davidpodhola** [comment]
Yes, for every single entity.

I looked into the code a little bit, but still not sure how are Resources constructed to try to find out why this is happening.
![screenshot from 2017-09-27 12-09-24](https://user-images.githubusercontent.com/436605/30908077-d317e422-a37c-11e7-8a05-f79db453d141.png)

**Comment by davidpodhola** [comment]
Found. The URL in `App.js` in `HydraAdmin` element must **NOT end with a slash (`/`) character**.

- Wrong: `entrypoint="http://127.0.0.1/"`
- Right: `entrypoint="http://127.0.0.1"`

**Comment by mauchede** [comment]
Hello @Dannebicque and @davidpodhola,

We updated the project (tag `v0.3.1`). You can now define the desired version of react (I suggest you to stay under react `15` to begin). Your `package.json` should look like:

```json
{
  "dependencies": {
    "@api-platform/admin": "^0.3.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "react-scripts": "^1.1.0"
  },
  ...
}
```

I tried an entrypoint with and without a slash (`/`) at the end. It works in all cases. If you use entrypoint for login, normalization, etc. I suggest you to "normalize" the entrypoint. In my own projects, I use something like this:

```js
// src/constants.js

const normalizeUrl = url => ('/' === url.slice(-1) ? url.substring(0, url.length - 1) : url);

export const API_ENTRYPOINT = normalizeUrl(process.env.REACT_APP_API_ENTRYPOINT);

// ...

// src/app.js

import { API_ENTRYPOINT } from './constants';

export default () => (
    <HydraAdmin
        entrypoint={API_ENTRYPOINT}
    />
);
```

---

As it works now, I will close this issue. Feel free to reopen it or to open a new issue if you have any problem.
